/* ============================================================
   小筑 · 阅读墙 & 影视墙 数据文件
   ------------------------------------------------------------
   ★ 如何添加/更新条目：修改下面的 READING（书/漫画）或
     MOVIES（电影/剧集）数组，或直接告诉墨鸦"《XX》读到xx%"
   ★ 字段说明（READING / MOVIES 通用）：
       title    标题（书名 / 片名）
       type     类型：READING 用「书 / 漫画」；MOVIES 用「电影 / 剧集」
       author   作者 / 导演（可省略）
       status   状态：
                  "reading" → 在读 / 在看
                  "done"    → 已读完 / 已看完
                  "wish"    → 想读 / 想看
       progress 进度：
                  READING 用数字表示百分比，如 42 表示读到 42%；
                  MOVIES 用文字表示，如 "S2E05" 或 " 看到 45 分钟"
                  （仅 status 为 reading 时显示进度条）
       rating   评分：0-5，支持 0.5（如 4.5），未评分填 0
       comment  一句话观后感 / 短评（可省略）
       cover    海报图片地址（相对路径，如 "posters/dune2.jpg"）。
                留空则显示渐变占位封面，之后拿到海报随时替换
       emoji    占位封面上的图标
   ============================================================ */

const READING = [
  /* ---------- 书：正在读（微信读书书架） ---------- */
  {
    title: "谁杀了她",
    type: "书",
    author: "东野圭吾",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/db-30210250.jpg",
    emoji: "🔪",
  },
  {
    title: "东野圭吾「加贺恭一郎」系列",
    type: "书",
    author: "东野圭吾",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/db-6746289.jpg",
    emoji: "🕵️",
  },
  {
    title: "人间椅子",
    type: "书",
    author: "江户川乱步",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/db-36049200.jpg",
    emoji: "🪑",
  },
  {
    title: "克苏鲁神话 I：克苏鲁的呼唤",
    type: "书",
    author: "H.P. 洛夫克拉夫特",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/db-26862626.jpg",
    emoji: "🐙",
  },
  {
    title: "怪画谜案",
    type: "书",
    author: "雨穴",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/db-36858240.jpg",
    emoji: "🖼️",
  },
  {
    title: "罗生门（读客三个圈经典文库）",
    type: "书",
    author: "芥川龙之介",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/db-26786416.jpg",
    emoji: "🚪",
  },
  {
    title: "嫌疑人 X 的献身",
    type: "书",
    author: "东野圭吾",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/db-3211779.jpg",
    emoji: "🧮",
  },
  /* ---------- 书：已读完 ---------- */
  {
    title: "恶意",
    type: "书",
    author: "东野圭吾",
    status: "done",
    progress: 100,
    rating: 0,
    comment: "",
    cover: "posters/db-26877752.jpg",
    emoji: "😈",
  },
  {
    title: "从前我死去的家",
    type: "书",
    author: "东野圭吾",
    status: "done",
    progress: 100,
    rating: 0,
    comment: "",
    cover: "posters/db-30245830.jpg",
    emoji: "🏚️",
  },

  /* ---------- 漫画：在读 ---------- */
  {
    title: "坂本日常",
    type: "漫画",
    author: "铃木祐斗",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-496617.jpg",
    emoji: "🥷",
  },
  {
    title: "電鋸人（全彩版）",
    type: "漫画",
    author: "藤本树",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-268279.jpg",
    emoji: "🪚",
  },
  {
    title: "端脑",
    type: "漫画",
    author: "壁水羽",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-112978.jpg",
    emoji: "🧠",
  },
  {
    title: "灌篮高手（完全版）",
    type: "漫画",
    author: "井上雄彦",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-18462.jpg",
    emoji: "🏀",
  },
  {
    title: "金田一少年事件簿 第二部 20 周年系列",
    type: "漫画",
    author: "佐藤文也 / 天树征丸",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-17200.jpg",
    emoji: "🔍",
  },
  {
    title: "金田一少年事件簿 第二部 新系列",
    type: "漫画",
    author: "佐藤文也 / 天树征丸",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-48108.jpg",
    emoji: "🔍",
  },
  {
    title: "金田一少年事件簿 第一部 File 系列（爱藏版）",
    type: "漫画",
    author: "佐藤文也 / 天树征丸",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-506306.jpg",
    emoji: "🔍",
  },
  {
    title: "金田一少年事件簿 R（第二部 R 系列）",
    type: "漫画",
    author: "佐藤文也 / 天树征丸",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-96861.jpg",
    emoji: "🔍",
  },
  {
    title: "金田一少年之事件簿 30th",
    type: "漫画",
    author: "佐藤文也 / 天树征丸",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-365622.jpg",
    emoji: "🔍",
  },
  {
    title: "迷宫饭",
    type: "漫画",
    author: "九井谅子",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-395378.jpg",
    emoji: "🍖",
  },
  {
    title: "人间失格",
    type: "漫画",
    author: "伊藤润二（原作：太宰治）",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-39199.jpg",
    emoji: "🌑",
  },
  {
    title: "杀戮都市",
    type: "漫画",
    author: "奥浩哉",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-35906.jpg",
    emoji: "🖤",
  },
  {
    title: "伊藤润二爱藏版",
    type: "漫画",
    author: "伊藤润二",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-316522.jpg",
    emoji: "🌀",
  },
  {
    title: "伊藤润二恐怖漫画精选",
    type: "漫画",
    author: "伊藤润二",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-4317.jpg",
    emoji: "👁️",
  },
  {
    title: "葬送的芙莉莲",
    type: "漫画",
    author: "阿部司（原作：山田钟人）",
    status: "reading",
    progress: 0,
    rating: 0,
    comment: "",
    cover: "posters/bgm-400602.jpg",
    emoji: "🧝",
  },
];

const MOVIES = [
  /* 影视记录暂空（黑羽 2026-10-05 确认旧 5 条都没看过，已清空）
     —— 之后用「片名 + 看到哪 + 评分」即可补录，墨鸦会自动抓海报 */
];

/* ============================================================
   游戏墙数据
   ★ 数据来源：Exophase 自动刮削（tools/scrape-exophase.js）
   ★ status：「playing」在玩 / 「done」已通关 / 「wish」想玩
   ★ progress：数字=完成度百分比（显示进度条）；文字=时长/关卡
   ★ platform：Steam / PS5 / PS4 / Switch（显示在卡片上）
   ★ 手写短评优先，刮削只补时长和封面
   ============================================================ */
const GAMES = [
  {
    title: "God of War",
    type: "游戏",
    genre: "动作冒险",
    platform: "PS4",
    status: "playing",
    progress: "27.1 小时 · 最近 2026-08",
    rating: 0,
    cover: "posters/steam-1593500.jpg",
    emoji: "🎮",
  },
  {
    title: "DEATH STRANDING DIRECTOR'S CUT",
    type: "游戏",
    genre: "动作冒险",
    platform: "PS5",
    status: "playing",
    progress: "71.8 小时 · 最近 2026-07",
    rating: 0,
    cover: "posters/steam-1850570.jpg",
    emoji: "🎮",
  },
  {
    title: "黑神话：悟空",
    type: "游戏",
    genre: "角色扮演",
    author: "游戏科学",
    platform: "PS5",
    status: "playing",
    progress: "40 小时 · 最近 2026-06",
    rating: 0,
    comment: "第三章的黄风岭配乐封神。手残党在虎先锋面前卡了两晚上。",
    cover: "posters/steam-2358720.jpg",
    emoji: "🐒",
  },
  {
    title: "Slay the Spire",
    type: "游戏",
    genre: "策略经营",
    author: "Mega Crit Games",
    platform: "Steam",
    status: "playing",
    progress: "7.8 小时 · 最近 2026-06",
    rating: 0,
    cover: "posters/steam-646570.jpg",
    emoji: "🎮",
  },
  {
    title: "Wallpaper Engine",
    type: "游戏",
    genre: "工具",
    author: "Kristjan Skutta",
    platform: "Steam",
    status: "playing",
    progress: "80 小时 · 最近 2026-06",
    rating: 0,
    cover: "posters/steam-431960.jpg",
    emoji: "🎮",
  },
  {
    title: "Lossless Scaling",
    type: "游戏",
    genre: "工具",
    platform: "Steam",
    status: "playing",
    progress: "4.4 小时 · 最近 2026-05",
    rating: 0,
    cover: "posters/steam-993090.jpg",
    emoji: "🎮",
  },
  {
    title: "Neverness to Everness",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "playing",
    progress: "4.2 小时 · 最近 2026-05",
    rating: 0,
    cover: "posters/bgm-game-503983.jpg",
    emoji: "🎮",
  },
  {
    title: "Call of Duty Modern Warfare",
    type: "游戏",
    genre: "射击",
    platform: "PS4 / PS5",
    status: "playing",
    progress: "18.3 小时 · 最近 2026-04",
    rating: 0,
    cover: "posters/steam-2000950.jpg",
    emoji: "🎮",
  },
  {
    title: "Crimson Desert Enhanced",
    type: "游戏",
    genre: "动作冒险",
    platform: "Steam",
    status: "playing",
    progress: "19.5 小时 · 最近 2026-04",
    rating: 0,
    cover: "posters/steam-3321460.jpg",
    emoji: "🎮",
  },
  {
    title: "Darkest Dungeon",
    type: "游戏",
    genre: "角色扮演",
    author: "Red Hook Studios",
    platform: "Steam",
    status: "playing",
    progress: "3.9 小时 · 最近 2026-04",
    rating: 0,
    cover: "posters/steam-262060.jpg",
    emoji: "🎮",
  },
  {
    title: "Ready or Not",
    type: "游戏",
    genre: "射击",
    author: "VOID Interactive",
    platform: "Steam",
    status: "playing",
    progress: "5.9 小时 · 最近 2026-04",
    rating: 0,
    cover: "posters/steam-1144200.jpg",
    emoji: "🎮",
  },
  {
    title: "It Takes Two",
    type: "游戏",
    genre: "独立游戏",
    platform: "PS5",
    status: "playing",
    progress: "51.4 小时 · 最近 2026-03",
    rating: 0,
    cover: "posters/steam-1426210.jpg",
    emoji: "🎮",
  },
  {
    title: "Resident Evil 2",
    type: "游戏",
    genre: "恐怖",
    author: "CAPCOM Co. Ltd.",
    platform: "Steam",
    status: "playing",
    progress: "21.3 小时 · 最近 2026-03",
    rating: 0,
    cover: "posters/steam-883710.jpg",
    emoji: "🎮",
  },
  {
    title: "Cyberpunk 2077",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "playing",
    progress: "7.3 小时 · 最近 2026-02",
    rating: 0,
    cover: "posters/steam-1091500.jpg",
    emoji: "🎮",
  },
  {
    title: "FINAL FANTASY VII REBIRTH",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "playing",
    progress: "86.6 小时 · 最近 2026-01",
    rating: 0,
    cover: "posters/steam-2909400.jpg",
    emoji: "🎮",
  },
  {
    title: "Red Dead Redemption 2",
    type: "游戏",
    genre: "动作冒险",
    author: "Rockstar Games",
    platform: "Steam",
    status: "playing",
    progress: "3.4 小时 · 最近 2025-12",
    rating: 0,
    cover: "posters/steam-1174180.jpg",
    emoji: "🎮",
  },
  {
    title: "Detroit: Become Human",
    type: "游戏",
    genre: "动作冒险",
    author: "Quantic Dream (original release)",
    platform: "Steam",
    status: "playing",
    progress: "16 小时 · 最近 2025-11",
    rating: 0,
    cover: "posters/steam-1222140.jpg",
    emoji: "🎮",
  },
  {
    title: "eFootball",
    type: "游戏",
    genre: "体育竞技",
    author: "Konami",
    platform: "PS5",
    status: "playing",
    progress: "1.5 小时 · 最近 2025-11",
    rating: 0,
    cover: "posters/bgm-game-625842.jpg",
    emoji: "🎮",
  },
  {
    title: "Where Winds Meet",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "playing",
    progress: "2.1 小时 · 最近 2025-11",
    rating: 0,
    cover: "posters/bgm-game-397705.jpg",
    emoji: "🎮",
  },
  {
    title: "Bongo Cat",
    type: "游戏",
    genre: "独立游戏",
    author: "Marcel Zurawka",
    platform: "Steam",
    status: "playing",
    progress: "30.9 小时 · 最近 2025-10",
    rating: 0,
    cover: "posters/steam-3419430.jpg",
    emoji: "🎮",
  },
  {
    title: "Yakuza 0",
    type: "游戏",
    genre: "动作冒险",
    author: "Sega Studios Australia",
    platform: "Steam",
    status: "playing",
    progress: "3.7 小时 · 最近 2025-10",
    rating: 0,
    cover: "posters/steam-638970.jpg",
    emoji: "🎮",
  },
  {
    title: "Persona 5 Royal",
    type: "游戏",
    genre: "角色扮演",
    author: "Atlus",
    platform: "Steam",
    status: "playing",
    progress: "34.8 小时 · 最近 2025-09",
    rating: 0,
    cover: "posters/steam-1687950.jpg",
    emoji: "🎮",
  },
  {
    title: "Sultan's Game",
    type: "游戏",
    genre: "策略经营",
    author: "Double Cross",
    platform: "Steam",
    status: "playing",
    progress: "7.9 小时 · 最近 2025-09",
    rating: 0,
    cover: "posters/steam-3117820.jpg",
    emoji: "🎮",
  },
  {
    title: "Diablo IV",
    type: "游戏",
    genre: "角色扮演",
    author: "Blizzard Entertainment",
    platform: "Steam",
    status: "playing",
    progress: "14.8 小时 · 最近 2025-07",
    rating: 0,
    cover: "posters/steam-2344520.jpg",
    emoji: "🎮",
  },
  {
    title: "FINAL FANTASY XVI",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "playing",
    progress: "63.8 小时 · 最近 2025-07",
    rating: 0,
    cover: "posters/steam-2515020.jpg",
    emoji: "🎮",
  },
  {
    title: "The Witcher 3: Wild Hunt",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "playing",
    progress: "1.6 小时 · 最近 2025-07",
    rating: 0,
    cover: "posters/steam-292030.jpg",
    emoji: "🎮",
  },
  {
    title: "Borderlands 3",
    type: "游戏",
    genre: "射击",
    author: "Gearbox Software LLC",
    platform: "PS5",
    status: "playing",
    progress: "1.9 小时 · 最近 2025-06",
    rating: 0,
    cover: "posters/steam-397540.jpg",
    emoji: "🎮",
  },
  {
    title: "DAVE THE DIVER",
    type: "游戏",
    genre: "策略经营",
    author: "MINTROCKET",
    platform: "Steam",
    status: "playing",
    progress: "5.3 小时 · 最近 2025-06",
    rating: 0,
    cover: "posters/steam-1868140.jpg",
    emoji: "🎮",
  },
  {
    title: "Metro Exodus",
    type: "游戏",
    genre: "射击",
    platform: "PS5",
    status: "playing",
    progress: "4.7 小时 · 最近 2025-06",
    rating: 0,
    cover: "posters/steam-412020.jpg",
    emoji: "🎮",
  },
  {
    title: "Monster Hunter: World",
    type: "游戏",
    genre: "动作冒险",
    author: "CAPCOM Co. Ltd.",
    platform: "Steam",
    status: "playing",
    progress: "51.2 小时 · 最近 2025-05",
    rating: 0,
    cover: "posters/steam-582010.jpg",
    emoji: "🎮",
  },
  {
    title: "The Last of Us Remastered",
    type: "游戏",
    genre: "动作冒险",
    platform: "PS4",
    status: "playing",
    progress: "6.6 小时 · 最近 2025-02",
    rating: 0,
    cover: "posters/bgm-game-490661.jpg",
    emoji: "🎮",
  },
  {
    title: "塞尔达传说：王国之泪",
    type: "游戏",
    genre: "动作冒险",
    author: "任天堂",
    platform: "Switch",
    status: "playing",
    progress: "刚玩了几个任务",
    rating: 0,
    comment: "刚玩了几个任务，攻略已整理成文。",
    cover: "img/cover-zelda_w.jpg",
    emoji: "🗺️",
    review: "zelda-shrine-guide",
  },
  {
    title: "博德之门 3",
    type: "游戏",
    genre: "角色扮演",
    author: "Larian Studios",
    platform: "Steam",
    status: "done",
    progress: "166.4 小时 · 最近 2026-08",
    rating: 5,
    comment: "年度游戏没有悬念。队友全员立体的 CRPG 天花板，二周目排队中。",
    cover: "posters/steam-1086940.jpg",
    emoji: "🎲",
  },
  {
    title: "星露谷物语",
    type: "游戏",
    genre: "策略经营",
    author: "ConcernedApe",
    platform: "Steam",
    status: "done",
    progress: "30.3 小时 · 最近 2025-10",
    rating: 4.5,
    comment: "电子布洛芬。压力大的时候回去种两天地，什么都好了。",
    cover: "posters/steam-413150.jpg",
    emoji: "🌾",
  },
  {
    title: "DYNASTY WARRIORS: ORIGINS",
    type: "游戏",
    genre: "动作冒险",
    author: "KOEI TECMO GAMES CO.",
    platform: "Steam",
    status: "wish",
    progress: "0.6 小时 · 最近 2026-06",
    rating: 0,
    cover: "posters/steam-2384580.jpg",
    emoji: "🎮",
  },
  {
    title: "Arknights: Endfield",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "wish",
    progress: "最近 2026-05",
    rating: 0,
    cover: "posters/bgm-game-374638.jpg",
    emoji: "🎮",
  },
  {
    title: "DSX",
    type: "游戏",
    genre: "工具",
    author: "Paliverse",
    platform: "Steam",
    status: "wish",
    progress: "0.8 小时 · 最近 2026-04",
    rating: 0,
    cover: "posters/steam-1812620.jpg",
    emoji: "🎮",
  },
  {
    title: "Live2DViewerEX",
    type: "游戏",
    genre: "工具",
    platform: "Steam",
    status: "wish",
    progress: "0.6 小时 · 最近 2026-02",
    rating: 0,
    cover: "posters/steam-616720.jpg",
    emoji: "🎮",
  },
  {
    title: "Horizon Zero Dawn Remastered",
    type: "游戏",
    genre: "动作冒险",
    author: "guerrilla games",
    platform: "Steam",
    status: "wish",
    progress: "0.8 小时 · 最近 2025-10",
    rating: 0,
    cover: "posters/steam-2561580.jpg",
    emoji: "🎮",
  },
  {
    title: "Spacewar",
    type: "游戏",
    genre: "独立游戏",
    platform: "Steam",
    status: "wish",
    progress: "0.2 小时 · 最近 2025-10",
    rating: 0,
    cover: "posters/steam-4989790.jpg",
    emoji: "🎮",
  },
  {
    title: "Delta Force",
    type: "游戏",
    genre: "射击",
    platform: "PS5",
    status: "wish",
    progress: "0.9 小时 · 最近 2025-09",
    rating: 0,
    cover: "posters/steam-2507950.jpg",
    emoji: "🎮",
  },
  {
    title: "Wuthering Waves",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "wish",
    progress: "最近 2025-09",
    rating: 0,
    cover: "posters/bgm-game-385208.jpg",
    emoji: "🎮",
  },
  {
    title: "Zenless Zone Zero",
    type: "游戏",
    genre: "角色扮演",
    platform: "PS5",
    status: "wish",
    progress: "0.2 小时 · 最近 2025-09",
    rating: 0,
    cover: "posters/bgm-game-380974.jpg",
    emoji: "🎮",
  },
  {
    title: "Uncharted 4: A Thief’s End",
    type: "游戏",
    genre: "动作冒险",
    platform: "PS4",
    status: "wish",
    progress: "0.1 小时 · 最近 2025-07",
    rating: 0,
    cover: "posters/steam-1659420.jpg",
    emoji: "🎮",
  },
  {
    title: "Grand Theft Auto V Enhanced",
    type: "游戏",
    genre: "动作冒险",
    author: "rockstar north",
    platform: "Steam",
    status: "wish",
    progress: "0.4 小时 · 最近 2025-05",
    rating: 0,
    cover: "posters/steam-3240220.jpg",
    emoji: "🎮",
  },
  {
    title: "The Last of Us Part I",
    type: "游戏",
    genre: "动作冒险",
    platform: "PS5",
    status: "wish",
    progress: "0.4 小时 · 最近 2024-12",
    rating: 0,
    cover: "posters/steam-1888930.jpg",
    emoji: "🎮",
  },
  {
    title: "艾尔登法环：黄金树幽影",
    type: "游戏",
    genre: "角色扮演",
    author: "FromSoftware",
    platform: "PS5",
    status: "wish",
    rating: 0,
    comment: "本体还没打通，DLC 先囤着。",
    cover: "posters/bgm-game-284100.jpg",
    emoji: "🗡️",
  },
];

/* ============================================================
   「全文观后感」链接约定
   ------------------------------------------------------------
   READING / MOVIES / GAMES 任意条目加一个字段：
       review: "对应博文 POSTS 数组里的 id"
   卡片上就会自动出现「→ 全文观后感」链接，跳到 post.html。
   长篇感想写好发给我，我负责：① 登记为博客文章 ② 墙上挂链接。
   ============================================================ */
